// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV616pkxfEzca-tc82PChA7tqW0-PWecY',
    appId: '1:1060083028142:web:a26aada6858c6c80da5d3f',
    messagingSenderId: '1060083028142',
    projectId: 'septeo',
    authDomain: 'septeo.firebaseapp.com',
    storageBucket: 'septeo.appspot.com',
    measurementId: 'G-6S0LPENN1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTWM1HLduhzS23v5u5J_x7Q6fM-540LQ',
    appId: '1:1060083028142:android:de97cd1876caa345da5d3f',
    messagingSenderId: '1060083028142',
    projectId: 'septeo',
    storageBucket: 'septeo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMq5DQNSn4ajN0WomRXUejVDDAMDx6-2U',
    appId: '1:1060083028142:ios:0dc5bdae68407950da5d3f',
    messagingSenderId: '1060083028142',
    projectId: 'septeo',
    storageBucket: 'septeo.appspot.com',
    iosClientId: '1060083028142-f1nnmps6jush9i0hf1m81s935iogsimp.apps.googleusercontent.com',
    iosBundleId: 'com.example.septeoTransport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMq5DQNSn4ajN0WomRXUejVDDAMDx6-2U',
    appId: '1:1060083028142:ios:2d72a333efc12833da5d3f',
    messagingSenderId: '1060083028142',
    projectId: 'septeo',
    storageBucket: 'septeo.appspot.com',
    iosClientId: '1060083028142-vrb6adpefdf90humcs9j0oju61sl16m4.apps.googleusercontent.com',
    iosBundleId: 'com.example.septeoTransport.RunnerTests',
  );
}
